language: python
python:
  - "3.5"
script:
  - pip install .

deploy:
  api_key:
    secure: UxmshxapayYyQ/NaGJe8NJfqRaUkVcQGQ/Olr6ymHtI7mBUDKdrZARp3nyuOSmrdfO7nzCDRsy7mldH5rCzP5iZxAloVX3qL4JgXuX9GSggTHLaSJGSoMMhg0tGyZ7scpCQIgJhHTOxt0mxGlC+Cg2f7LCZAcW2V0YTtk4QXhrPUDK3ZrU8Lrtjy0FaQOXSSi2AxP2BKdqphUs2pHL/TeLD6eUSpQg52+O0u0rsL7o+/WugjfLIa2KtzzNZtLTiUrgZhwpQvs8ukF9uaP8FZR1p5Yx4o7sVSWFR1d0R7bXcJpWfwv4CmlxhCwHa0tva2pQ3vxEVsJGiK/FuTtBCjdeVjFe3FSWpZMmQjRkuGthrhrRtitz4vU/AQJiL3VVd5gBdxgO3b++5Qzhu9uikMl3Ul4F9F187rm0Yde3f99bge3YzGfeDWEgYO0tNCXpp0W32Grm2DDsmoRytx8YuiJDZlV08dhY7m36qpTYB0Xz8vd2KffyqwJ0QBKMLURXOaye7vwts0AIFaGAu3+xFe3w0yJm9od7/ukQ21A6ymPiX4fZG2MIqadetnQUlKM9A3q+kh0pshFB67UdbwqFQiCFHoT128ApMuTUr0HPzbDgM3GRsE/ZVDcolAYbl4VUJso3sSkqqXjUSvTCHBljsfDz+GWonWcNZ28g7Dn0/KR0g= 
  provider: releases
  file: "README.md"
  skip_cleanup: true
  overwrite: true
  draft: true
  name: $TRAVIS_TAG
  tag: $TRAVIS_TAG
  body: |
      This is the $TRAVIS_TAG release of this application
      More lines here
      <br> and even more
      <br> the end
  on: 
    repo: glasnt/travis-test
    tags: true
